-- banks_reviews_dump.sql

-- Drop tables if they exist
DROP TABLE reviews CASCADE CONSTRAINTS;
DROP TABLE banks CASCADE CONSTRAINTS;

-- Create banks table
CREATE TABLE banks (
    bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR2(100) NOT NULL
);

-


-- Create reviews table
CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(user_id),
    bank_id NUMBER REFERENCES banks(bank_id),
    rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    review_text VARCHAR2(500),
    review_date DATE DEFAULT SYSDATE
);

-- Insert sample data
INSERT INTO banks (bank_name) VALUES ('Kuda');
INSERT INTO banks (bank_name) VALUES ('PiggyVest');



INSERT INTO reviews (user_id, bank_id, rating, review_text) VALUES (1, 1, 5, 'Excellent experience!');
INSERT INTO reviews (user_id, bank_id, rating, review_text) VALUES (2, 2, 4, 'Pretty good, but needs improvement.');

COMMIT;
